defaults:
  #host: "192.168.100.37"
  host: "212.106.181.37"
  port: 9400
  endpoint: "rpc"
  retry_delay: 1 # seconds to wait before trying again on failure
  verbose: true # whether to print verbose output
